version: '3'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app:ro
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - mongod
    # restart: on-failure

  mongod:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_db:/data/db:rw
    ports:
      - '27017:27017'

volumes:
  mongo_db: